default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "sample_app") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "development_password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "sample_app_development") %>

  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DB_NAME", "sample_app_development_queue") %>
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "sample_app_test") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "sample_app_production") %>

  cache:
    <<: *default
    database: <%= ENV.fetch("CACHE_DB_NAME", "sample_app_production_cache") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DB_NAME", "sample_app_production_queue") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV.fetch("CABLE_DB_NAME", "sample_app_production_cable") %>
    migrations_paths: db/cable_migrate